language: node_js
node_js:
- '10'
os: linux
notifications:
  email:
    recipients:
    - zhouyuexie@gmail.com # 更改成你自己的邮箱
    on_success: never
    on_failure: always
branches:
  only:
  - master
addons:
  ssh_known_hosts: ip # 更新你自己的ip或者域名
before_install:
- openssl aes-256-cbc -K $encrypted_9db66526d0d0_key -iv $encrypted_9db66526d0d0_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: yarn deploy
  on:
    branch: master
